### ISSUE TITLE
App Crashes when Attempting to Select Non-Existent Characters at End of Text

### ISSUE THREAD

**Issue by kitakkun** [kitakkun/JotDraft#6]
## Error log
```
FATAL EXCEPTION: main
Process: com.github.kitakkun.noteapp, PID: 19141
java.lang.IllegalArgumentException: lineIndex(3) is out of bounds [0, 3)
	at androidx.compose.ui.text.MultiParagraph.requireLineIndexInRange(MultiParagraph.kt:783)
	at androidx.compose.ui.text.MultiParagraph.getLineLeft(MultiParagraph.kt:659)
	at androidx.compose.ui.text.TextLayoutResult.getLineLeft(TextLayoutResult.kt:439)
	at androidx.compose.foundation.text.TextLayoutResultProxy.isPositionOnText-k-4lQ0M(TextLayoutResultProxy.kt:65)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager$touchSelectionObserver$1.onStart-k-4lQ0M(TextFieldSelectionManager.kt:181)
	at androidx.compose.foundation.text.LongPressTextDragObserverKt$detectDragGesturesAfterLongPressWithObserver$2.invoke-k-4lQ0M(LongPressTextDragObserver.kt:68)
	at androidx.compose.foundation.text.LongPressTextDragObserverKt$detectDragGesturesAfterLongPressWithObserver$2.invoke(LongPressTextDragObserver.kt:62)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt$detectDragGesturesAfterLongPress$5.invokeSuspend(DragGestureDetector.kt:238)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine$withTimeout$job$1.invokeSuspend(SuspendingPointerInputFilter.kt:624)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@5079581, androidx.compose.runtime.BroadcastFrameClock@68e2626, StandaloneCoroutine{Cancelling}@18a0267, AndroidUiDispatcher@7289814]
```

## How to reproduce

1. Specify base style to Title
2. input some text
3. insert linebreak
4. change base style to the other
5. input some text 
6. insert linebreak
7. try to select the end of line(long press at the end of document)

**Comment by kitakkun** [comment]
seems like this problem occurs when we try to select an empty text in a paragraph style.

**Comment by kitakkun** [comment]
one solution is insert return when `start == end` before the second `addStyle()` here.

https://github.com/kitakkun/NoteApp/blob/0c7be69d7d601d3f2f94b72c077fff0c1d57b0e2/app/src/main/java/com/github/kitakkun/noteapp/ui/page/editor/ext/AnnotatedString.kt#L20-L40

**Comment by kitakkun** [comment]
solution 2: create custom OffsetMapping class.
I'm not sure if this approach works well, but I think OffsetMapping determines what part of visible text can be selected or not.

**Comment by kitakkun** [comment]
submitted an issue on IssueTracker https://issuetracker.google.com/issues/289121264
waiting for a feedback from the team.
